\NeedsTexFormat{LaTeX2e}
\ProvidesClass{mlatext}[2025/09/22 Mathematics LaTeX Template]

% General Formatting
\RequirePackage{hyperref}
\RequirePackage{fancyhdr}

% Math Formatting Packages
\RequirePackage{amsthm}
\RequirePackage{amssymb}
\RequirePackage{amsmath}

% Graphics Packages
\RequirePackage{tikz}
\RequirePackage{tikz-3dplot}
\RequirePackage{subcaption}

% Coloring
\RequirePackage{xcolor}
\RequirePackage{tcolorbox}
